(Update and Add) -> home_screen & container_widget
What : Creating an complex widget that is heavely used in the container_widget

why: To make the code more readable and implement the given UI by code

Error: The chances are high the code can produce an Error
    cause: Simple it is called manual patching
    solution: Use the code as a reference and try to implement it yourself